use_frameworks!

source 'http://gitlab.fallrainy.top/root/XDBSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'WLDebugingOverlay_Example' do
  pod 'WLDebugingOverlay'

  target 'WLDebugingOverlay_Tests' do
    inherit! :search_paths

    
  end
end
